name: branch build

on:
  pull_request:
    branches:
      - "main"

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.15"

      - name: Install modules
        run: yarn install --frozen-lockfile

      - name: trufflehog-actions-scan
        uses: edplato/trufflehog-actions-scan@master

      - name: Build solution
        run: yarn build

      - name: Build image
        run: docker build . -t security-tools

      - name: Scan image
        uses: anchore/scan-action@v2
        with:
          image: "security-tools:latest"

      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./infrastructure
          framework: terraform 

      - name: Run tests with coverage
        run: yarn test

      - name: Run Insider
        uses: insidersec/insider-action@v0
        with:
            security: 100
            technology: javascript
            target: ./src

      - name: Run eslint
        run: yarn lint

      - name: Audit
        run: yarn audit
